### ISSUE TITLE
Errors when installing singularity environment

### ISSUE THREAD

**Issue by JunhaoZhu0220** [RicercarG/NYU-Greene-HPC-Cheatsheet#1]
When I was installing a singularity environment, the errors in the screenshot below is showed:
<img width="1018" alt="image" src="https://github.com/RicercarG/NYU-Greene-HPC-Cheatsheet/assets/129193941/294cb882-fc17-4ac1-ad1e-e25a2bfa2386">
How to fix this issue?

**Comment by RicercarG** [comment]
I also noticed this problem when using the chslauncher myself. It seems to happen on some of cpu/gpu nodes by chance.

To solve this problem, I made an update for a quick fix at 2024.4.7. So please first double check if you are using the latest chslauncher.sh.

Then, you can check [this trouble shooting wiki](https://github.com/RicercarG/NYU-Greene-HPC-Cheatsheet/wiki/Trouble-Shooting#conda-environment-installation-failed). Basically what you should do is running `chslauncher.sh` with argument `--no-check-certificate`. In your case, the singularity environment has already been created, so you can select `reinstall conda inside the singularity` after typing your environment folder name.

**Comment by JunhaoZhu0220** [comment]
`./chslauncher.sh --no-check-certificate` is working to solve this issue, thank u!
